const translations = {
  es: {
    metaDescription: "Página simple para explicar qué es Moodle Student Analyzer, para qué sirve y cómo usarlo.",
    headerTag: "Análisis simple de Moodle",
    navIdea: "Idea",
    navUse: "Cómo usarla",
    navAnalysis: "Análisis",
    navSummary: "Resumen",
    heroEyebrow: "Análisis simple de Moodle",
    heroTitle: "Una aplicación para entender mejor lo que pasa en un curso de Moodle.",
    heroLead: "Lee la información del campus, resume la actividad del alumnado y ayuda a detectar quién necesita seguimiento antes.",
    downloadButton: "Descargar la app",
    downloadUseLink: "Ver cómo usarla",
    downloadNote: "Descarga directa del ejecutable para Windows, sin instalación.",
    ideaTitle: "La idea",
    ideaBody1: "Moodle guarda mucha información, pero no siempre es fácil verla de forma clara. Esta aplicación junta lo importante en una sola vista.",
    ideaBody2: "El objetivo es pasar de muchos datos dispersos a una lectura rápida del curso, con señales útiles para seguimiento y toma de decisiones.",
    usefulnessTitle: "Para qué sirve",
    usefulness1: "Ver rápidamente el estado general de un curso.",
    usefulness2: "Detectar alumnado con poca actividad, bajo rendimiento o más riesgo.",
    usefulness3: "Revisar cada estudiante con más contexto y menos ruido.",
    usefulness4: "Generar informes para seguimiento docente, coordinación y tutorías.",
    howTitle: "Cómo usarla",
    how1: "Abre la aplicación y escribe la URL de tu Moodle.",
    how2: "Conecta con un token o genéralo con usuario y contraseña si no lo tienes.",
    how3: "Selecciona el curso, ajusta la nota mínima para aprobar si hace falta y lanza el análisis.",
    how4: "Consulta el dashboard, las gráficas, el detalle del alumnado y los informes.",
    insideTitle: "Cómo funciona",
    inside1: "Se conecta a los web services de Moodle en modo lectura.",
    inside2: "Recoge datos de estudiantes, tareas, cuestionarios, foros, actividad y progreso, y omite métricas que no aplican al curso.",
    inside3: "Calcula métricas, niveles de riesgo y señales de seguimiento usando el umbral de aprobado configurado.",
    inside4: "Presenta el resultado en paneles, gráficas e informes fáciles de interpretar.",
    analysisTitle: "Análisis, gráficas e informes",
    analysis1: "Análisis general del curso con alumnado total, engagement medio, entregas, actividad reciente y distribución de riesgo adaptada a lo que realmente tiene el curso.",
    analysis2: "Análisis por estudiante con riesgo, engagement, progreso, entregas, uso de cuestionarios, participación en foros y tendencia de notas, usando la nota mínima configurada como referencia.",
    analysis3: "Gráficas de distribución, comparación y correlación para entender de un vistazo el comportamiento del grupo.",
    analysis4: "Visualizaciones para detectar alumnado con mayor riesgo, menor actividad o menor seguimiento, sin sobredimensionar avisos leves cuando la nota está claramente por encima del aprobado.",
    analysis5: "Informes por curso, por tarea y por estudiante para revisar casos concretos con un resumen útil y ajustado a las métricas disponibles.",
    analysis6: "Si alguien necesita otro tipo de análisis o informe, puede solicitarlo para adaptarlo a una necesidad real.",
    summaryTitle: "En una frase",
    summaryBody: "Moodle Student Analyzer sirve para convertir los datos de Moodle en una vista clara de lo que ocurre en un curso y ayudar a decidir dónde actuar primero.",
  },
  gl: {
    metaDescription: "Páxina simple para explicar que é Moodle Student Analyzer, para que serve e como usalo.",
    headerTag: "Análise simple de Moodle",
    navIdea: "Idea",
    navUse: "Como usala",
    navAnalysis: "Análises",
    navSummary: "Resumo",
    heroEyebrow: "Análise simple de Moodle",
    heroTitle: "Unha aplicación para entender mellor o que pasa nun curso de Moodle.",
    heroLead: "Le a información do campus, resume a actividade do alumnado e axuda a detectar quen necesita seguimento antes.",
    downloadButton: "Descargar a app",
    downloadUseLink: "Ver como usala",
    downloadNote: "Descarga directa do executábel para Windows, sen instalación.",
    ideaTitle: "A idea",
    ideaBody1: "Moodle garda moita información, pero non sempre é doado vela de forma clara. Esta aplicación xunta o importante nunha soa vista.",
    ideaBody2: "O obxectivo é pasar de moitos datos dispersos a unha lectura rápida do curso, con sinais útiles para seguimento e toma de decisións.",
    usefulnessTitle: "Para que serve",
    usefulness1: "Ver rapidamente o estado xeral dun curso.",
    usefulness2: "Detectar alumnado con pouca actividade, baixo rendemento ou máis risco.",
    usefulness3: "Revisar cada estudante con máis contexto e menos ruído.",
    usefulness4: "Xerar informes para seguimento docente, coordinación e titorías.",
    howTitle: "Como usala",
    how1: "Abre a aplicación e escribe a URL do teu Moodle.",
    how2: "Conecta cun token ou xérao con usuario e contrasinal se non o tes.",
    how3: "Selecciona o curso, axusta a nota mínima para aprobar se fai falta e lanza a análise.",
    how4: "Consulta o dashboard, as gráficas, o detalle do alumnado e os informes.",
    insideTitle: "Como funciona",
    inside1: "Conéctase aos web services de Moodle en modo lectura.",
    inside2: "Recolle datos de estudantes, tarefas, cuestionarios, foros, actividade e progreso, e omite métricas que non aplican ao curso.",
    inside3: "Calcula métricas, niveis de risco e sinais de seguimento usando o limiar de aprobado configurado.",
    inside4: "Presenta o resultado en paneis, gráficas e informes fáciles de interpretar.",
    analysisTitle: "Análises, gráficas e informes",
    analysis1: "Análise xeral do curso con alumnado total, engagement medio, entregas, actividade recente e distribución do risco adaptada ao que realmente ten o curso.",
    analysis2: "Análise por estudante con risco, engagement, progreso, entregas, uso de cuestionarios, participación en foros e tendencia das notas, usando a nota mínima configurada como referencia.",
    analysis3: "Gráficas de distribución, comparación e correlación para entender dunha ollada o comportamento do grupo.",
    analysis4: "Visualizacións para detectar alumnado con maior risco, menor actividade ou menor seguimento, sen sobredimensionar avisos leves cando a nota está claramente por enriba do aprobado.",
    analysis5: "Informes por curso, por tarefa e por estudante para revisar casos concretos cun resumo útil e axustado ás métricas dispoñibles.",
    analysis6: "Se alguén necesita outro tipo de análise ou informe, pode solicitalo para adaptalo a unha necesidade real.",
    summaryTitle: "Nunha frase",
    summaryBody: "Moodle Student Analyzer serve para converter os datos de Moodle nunha vista clara do que ocorre nun curso e axudar a decidir onde actuar primeiro.",
  },
  en: {
    metaDescription: "Simple page explaining what Moodle Student Analyzer is, what it is for, and how to use it.",
    headerTag: "Simple Moodle analysis",
    navIdea: "Idea",
    navUse: "How to use it",
    navAnalysis: "Analysis",
    navSummary: "Summary",
    heroEyebrow: "Simple Moodle analysis",
    heroTitle: "An application to better understand what is happening in a Moodle course.",
    heroLead: "It reads campus data, summarizes student activity, and helps detect who needs follow-up first.",
    downloadButton: "Download the app",
    downloadUseLink: "See how to use it",
    downloadNote: "Direct download of the Windows executable, with no installation required.",
    ideaTitle: "The idea",
    ideaBody1: "Moodle stores a lot of information, but it is not always easy to read clearly. This application brings the important parts together in one view.",
    ideaBody2: "The goal is to move from scattered data to a quick reading of the course, with useful signals for follow-up and decision-making.",
    usefulnessTitle: "What it is for",
    usefulness1: "Quickly see the overall state of a course.",
    usefulness2: "Detect students with low activity, poor performance, or higher risk.",
    usefulness3: "Review each student with more context and less noise.",
    usefulness4: "Generate reports for teaching follow-up, coordination, and tutoring.",
    howTitle: "How to use it",
    how1: "Open the application and enter your Moodle URL.",
    how2: "Connect with a token or generate one with username and password if you do not have it.",
    how3: "Select the course, adjust the passing grade if needed, and start the analysis.",
    how4: "Review the dashboard, charts, student details, and reports.",
    insideTitle: "How it works",
    inside1: "It connects to Moodle web services in read-only mode.",
    inside2: "It collects data about students, assignments, quizzes, forums, activity, and progress, and skips metrics that do not apply to that course.",
    inside3: "It calculates metrics, risk levels, and follow-up signals using the configured passing threshold.",
    inside4: "It presents the result in panels, charts, and reports that are easy to interpret.",
    analysisTitle: "Analysis, charts, and reports",
    analysis1: "General course analysis with total students, average engagement, submissions, recent activity, and a risk distribution adapted to what the course actually contains.",
    analysis2: "Student analysis with risk, engagement, progress, submissions, quiz use, forum participation, and grade trends, using the configured passing grade as reference.",
    analysis3: "Distribution, comparison, and correlation charts to understand group behavior at a glance.",
    analysis4: "Visualizations to detect students with higher risk, lower activity, or weaker follow-up without overstating mild warnings when grades are clearly above the pass mark.",
    analysis5: "Course, assignment, and student reports to review specific cases with a useful summary tailored to the available metrics.",
    analysis6: "If someone needs another kind of analysis or report, they can request it so it fits a real need.",
    summaryTitle: "In one sentence",
    summaryBody: "Moodle Student Analyzer turns Moodle data into a clear view of what is happening in a course and helps decide where to act first.",
  },
  fr: {
    metaDescription: "Page simple pour expliquer ce qu'est Moodle Student Analyzer, à quoi il sert et comment l'utiliser.",
    headerTag: "Analyse simple de Moodle",
    navIdea: "Idée",
    navUse: "Utilisation",
    navAnalysis: "Analyses",
    navSummary: "Résumé",
    heroEyebrow: "Analyse simple de Moodle",
    heroTitle: "Une application pour mieux comprendre ce qui se passe dans un cours Moodle.",
    heroLead: "Elle lit les données du campus, résume l'activité des étudiants et aide à détecter qui a besoin d'un suivi en premier.",
    downloadButton: "Télécharger l'application",
    downloadUseLink: "Voir comment l'utiliser",
    downloadNote: "Téléchargement direct de l'exécutable Windows, sans installation.",
    ideaTitle: "L'idée",
    ideaBody1: "Moodle stocke beaucoup d'informations, mais il n'est pas toujours facile de les lire clairement. Cette application rassemble l'essentiel dans une seule vue.",
    ideaBody2: "L'objectif est de passer de données dispersées à une lecture rapide du cours, avec des signaux utiles pour le suivi et la prise de décision.",
    usefulnessTitle: "À quoi cela sert",
    usefulness1: "Voir rapidement l'état général d'un cours.",
    usefulness2: "Détecter les étudiants avec peu d'activité, de faibles résultats ou plus de risque.",
    usefulness3: "Revoir chaque étudiant avec plus de contexte et moins de bruit.",
    usefulness4: "Générer des rapports pour le suivi pédagogique, la coordination et le tutorat.",
    howTitle: "Comment l'utiliser",
    how1: "Ouvrez l'application et saisissez l'URL de votre Moodle.",
    how2: "Connectez-vous avec un jeton ou générez-en un avec identifiant et mot de passe si vous ne l'avez pas.",
    how3: "Sélectionnez le cours, ajustez si besoin la note minimale de validation et lancez l'analyse.",
    how4: "Consultez le tableau de bord, les graphiques, le détail des étudiants et les rapports.",
    insideTitle: "Comment cela fonctionne",
    inside1: "Elle se connecte aux web services de Moodle en mode lecture seule.",
    inside2: "Elle recueille des données sur les étudiants, devoirs, quiz, forums, activité et progression, et ignore les métriques qui ne s'appliquent pas au cours.",
    inside3: "Elle calcule des métriques, des niveaux de risque et des signaux de suivi en utilisant le seuil de validation configuré.",
    inside4: "Elle présente le résultat dans des panneaux, graphiques et rapports faciles à interpréter.",
    analysisTitle: "Analyses, graphiques et rapports",
    analysis1: "Analyse générale du cours avec nombre total d'étudiants, engagement moyen, remises, activité récente et distribution du risque adaptée à ce que le cours contient réellement.",
    analysis2: "Analyse par étudiant avec risque, engagement, progression, remises, usage des quiz, participation aux forums et tendance des notes, en utilisant la note minimale configurée comme référence.",
    analysis3: "Graphiques de distribution, comparaison et corrélation pour comprendre le comportement du groupe d'un coup d'œil.",
    analysis4: "Visualisations pour détecter les étudiants avec plus de risque, moins d'activité ou moins de suivi, sans exagérer des alertes légères quand la note est clairement au-dessus du seuil de validation.",
    analysis5: "Rapports par cours, par devoir et par étudiant pour revoir des cas concrets avec un résumé utile et adapté aux métriques disponibles.",
    analysis6: "Si quelqu'un a besoin d'un autre type d'analyse ou de rapport, il peut le demander afin de l'adapter à un besoin réel.",
    summaryTitle: "En une phrase",
    summaryBody: "Moodle Student Analyzer transforme les données Moodle en une vue claire de ce qui se passe dans un cours et aide à décider où agir d'abord.",
  },
  de: {
    metaDescription: "Einfache Seite, die erklärt, was Moodle Student Analyzer ist, wofür es dient und wie man es benutzt.",
    headerTag: "Einfache Moodle-Analyse",
    navIdea: "Idee",
    navUse: "Verwendung",
    navAnalysis: "Analysen",
    navSummary: "Kurzfassung",
    heroEyebrow: "Einfache Moodle-Analyse",
    heroTitle: "Eine Anwendung, um besser zu verstehen, was in einem Moodle-Kurs passiert.",
    heroLead: "Sie liest Campus-Daten, fasst die Aktivität der Studierenden zusammen und hilft zu erkennen, wer zuerst Betreuung braucht.",
    downloadButton: "App herunterladen",
    downloadUseLink: "Verwendung ansehen",
    downloadNote: "Direkter Download der Windows-EXE, ohne Installation.",
    ideaTitle: "Die Idee",
    ideaBody1: "Moodle speichert viele Informationen, aber sie sind nicht immer leicht klar zu lesen. Diese Anwendung bringt das Wichtige in einer Ansicht zusammen.",
    ideaBody2: "Das Ziel ist, von verstreuten Daten zu einer schnellen Kurslesart zu kommen, mit nützlichen Signalen für Betreuung und Entscheidungen.",
    usefulnessTitle: "Wofür es dient",
    usefulness1: "Den allgemeinen Zustand eines Kurses schnell sehen.",
    usefulness2: "Studierende mit wenig Aktivität, schwacher Leistung oder höherem Risiko erkennen.",
    usefulness3: "Jede Person mit mehr Kontext und weniger Rauschen prüfen.",
    usefulness4: "Berichte für Lehrbetreuung, Koordination und Tutorien erzeugen.",
    howTitle: "So wird es benutzt",
    how1: "Öffne die Anwendung und gib deine Moodle-URL ein.",
    how2: "Verbinde dich mit einem Token oder erzeuge eines mit Benutzername und Passwort, falls du keines hast.",
    how3: "Wähle den Kurs aus, passe bei Bedarf die Bestehensgrenze an und starte die Analyse.",
    how4: "Prüfe Dashboard, Diagramme, Detailansicht der Studierenden und Berichte.",
    insideTitle: "Wie es funktioniert",
    inside1: "Es verbindet sich im Nur-Lesen-Modus mit den Moodle-Webservices.",
    inside2: "Es sammelt Daten über Studierende, Aufgaben, Quizze, Foren, Aktivität und Fortschritt und lässt Kennzahlen weg, die für den Kurs nicht gelten.",
    inside3: "Es berechnet Kennzahlen, Risikostufen und Betreuungssignale mit der konfigurierten Bestehensgrenze.",
    inside4: "Es zeigt das Ergebnis in leicht lesbaren Panels, Diagrammen und Berichten.",
    analysisTitle: "Analysen, Diagramme und Berichte",
    analysis1: "Allgemeine Kursanalyse mit Gesamtzahl der Studierenden, durchschnittlichem Engagement, Abgaben, aktueller Aktivität und einer Risikoverteilung, die auf den tatsächlichen Kursinhalt abgestimmt ist.",
    analysis2: "Analyse pro Studierendem mit Risiko, Engagement, Fortschritt, Abgaben, Quiz-Nutzung, Forenbeteiligung und Notentrend, wobei die konfigurierte Bestehensnote als Referenz dient.",
    analysis3: "Verteilungs-, Vergleichs- und Korrelationsdiagramme, um das Gruppenverhalten auf einen Blick zu verstehen.",
    analysis4: "Visualisierungen, um Studierende mit hohem Risiko, niedriger Aktivität oder schwächerer Betreuung zu erkennen, ohne milde Warnungen zu überzeichnen, wenn die Note klar über der Bestehensgrenze liegt.",
    analysis5: "Kurs-, Aufgaben- und Personenberichte, um konkrete Fälle mit einer nützlichen Zusammenfassung zu prüfen, die zu den verfügbaren Kennzahlen passt.",
    analysis6: "Wenn jemand eine andere Art von Analyse oder Bericht braucht, kann er sie anfordern, damit sie zu einem realen Bedarf passt.",
    summaryTitle: "In einem Satz",
    summaryBody: "Moodle Student Analyzer macht aus Moodle-Daten eine klare Sicht auf das, was in einem Kurs passiert, und hilft zu entscheiden, wo zuerst gehandelt werden sollte.",
  },
  ca: {
    metaDescription: "Pàgina simple per explicar què és Moodle Student Analyzer, per a què serveix i com usar-lo.",
    headerTag: "Anàlisi simple de Moodle",
    navIdea: "Idea",
    navUse: "Com usar-la",
    navAnalysis: "Anàlisi",
    navSummary: "Resum",
    heroEyebrow: "Anàlisi simple de Moodle",
    heroTitle: "Una aplicació per entendre millor el que passa en un curs de Moodle.",
    heroLead: "Llegeix la informació del campus, resumeix l'activitat de l'alumnat i ajuda a detectar qui necessita seguiment abans.",
    downloadButton: "Descarregar l'app",
    downloadUseLink: "Veure com usar-la",
    downloadNote: "Descàrrega directa de l'executable de Windows, sense instal·lació.",
    ideaTitle: "La idea",
    ideaBody1: "Moodle desa molta informació, però no sempre és fàcil veure-la de forma clara. Aquesta aplicació ajunta l'important en una sola vista.",
    ideaBody2: "L'objectiu és passar de moltes dades disperses a una lectura ràpida del curs, amb senyals útils per a seguiment i presa de decisions.",
    usefulnessTitle: "Per a què serveix",
    usefulness1: "Veure ràpidament l'estat general d'un curs.",
    usefulness2: "Detectar alumnat amb poca activitat, baix rendiment o més risc.",
    usefulness3: "Revisar cada estudiant amb més context i menys soroll.",
    usefulness4: "Generar informes per a seguiment docent, coordinació i tutories.",
    howTitle: "Com usar-la",
    how1: "Obre l'aplicació i escriu l'URL del teu Moodle.",
    how2: "Connecta't amb un token o genera'n un amb usuari i contrasenya si no el tens.",
    how3: "Selecciona el curs, ajusta la nota mínima per aprovar si cal i llança l'anàlisi.",
    how4: "Consulta el dashboard, les gràfiques, el detall de l'alumnat i els informes.",
    insideTitle: "Com funciona",
    inside1: "Es connecta als web services de Moodle en mode de lectura.",
    inside2: "Recull dades d'estudiants, tasques, qüestionaris, fòrums, activitat i progrés, i omet mètriques que no apliquen al curs.",
    inside3: "Calcula mètriques, nivells de risc i senyals de seguiment fent servir el llindar d'aprovat configurat.",
    inside4: "Presenta el resultat en panells, gràfiques i informes fàcils d'interpretar.",
    analysisTitle: "Anàlisi, gràfiques i informes",
    analysis1: "Anàlisi general del curs amb alumnat total, engagement mitjà, lliuraments, activitat recent i distribució de risc adaptada al que realment té el curs.",
    analysis2: "Anàlisi per estudiant amb risc, engagement, progrés, lliuraments, ús de qüestionaris, participació en fòrums i tendència de notes, fent servir la nota mínima configurada com a referència.",
    analysis3: "Gràfiques de distribució, comparació i correlació per entendre d'una ullada el comportament del grup.",
    analysis4: "Visualitzacions per detectar alumnat amb més risc, menys activitat o menys seguiment, sense sobredimensionar avisos lleus quan la nota està clarament per sobre de l'aprovat.",
    analysis5: "Informes per curs, per tasca i per estudiant per revisar casos concrets amb un resum útil i ajustat a les mètriques disponibles.",
    analysis6: "Si algú necessita un altre tipus d'anàlisi o informe, el pot sol·licitar per adaptar-lo a una necessitat real.",
    summaryTitle: "En una frase",
    summaryBody: "Moodle Student Analyzer serveix per convertir les dades de Moodle en una vista clara del que passa en un curs i ajudar a decidir on actuar primer.",
  },
  eu: {
    metaDescription: "Orrialde sinplea Moodle Student Analyzer zer den, zertarako balio duen eta nola erabili azaltzeko.",
    headerTag: "Moodle analisi sinplea",
    navIdea: "Ideia",
    navUse: "Nola erabili",
    navAnalysis: "Analisiak",
    navSummary: "Laburpena",
    heroEyebrow: "Moodle analisi sinplea",
    heroTitle: "Moodle ikastaro batean zer gertatzen den hobeto ulertzeko aplikazioa.",
    heroLead: "Campuseko informazioa irakurtzen du, ikasleen jarduera laburbiltzen du eta lehenengo nork behar duen jarraipena antzematen laguntzen du.",
    downloadButton: "Aplikazioa deskargatu",
    downloadUseLink: "Ikusi nola erabili",
    downloadNote: "Windows exekutagarriaren deskarga zuzena, instalaziorik gabe.",
    ideaTitle: "Ideia",
    ideaBody1: "Moodlek informazio asko gordetzen du, baina ez da beti erraza modu argian ikustea. Aplikazio honek garrantzitsuena ikuspegi bakarrean biltzen du.",
    ideaBody2: "Helburua da sakabanatutako datuetatik ikastaroaren irakurketa azkar batera pasatzea, jarraipenerako eta erabakiak hartzeko seinale erabilgarriekin.",
    usefulnessTitle: "Zertarako balio du",
    usefulness1: "Ikastaro baten egoera orokorra azkar ikusteko.",
    usefulness2: "Jarduera gutxiago, errendimendu txikiagoa edo arrisku handiagoa duten ikasleak antzemateko.",
    usefulness3: "Ikasle bakoitza testuinguru gehiagorekin eta zarata gutxiagorekin berrikusteko.",
    usefulness4: "Irakasleen jarraipenerako, koordinaziorako eta tutoretzarako txostenak sortzeko.",
    howTitle: "Nola erabili",
    how1: "Ireki aplikazioa eta idatzi zure Moodle URL-a.",
    how2: "Konektatu token batekin edo sortu bat erabiltzailearekin eta pasahitzarekin ez baduzu.",
    how3: "Hautatu ikastaroa, behar bada egokitu gainditzeko gutxieneko nota, eta hasi analisia.",
    how4: "Begiratu dashboard-a, grafikoak, ikasleen xehetasunak eta txostenak.",
    insideTitle: "Nola funtzionatzen du",
    inside1: "Moodle web services zerbitzuetara irakurketa moduan konektatzen da.",
    inside2: "Ikasleei, atazei, quiz-ei, foroei, jarduerari eta aurrerapenari buruzko datuak jasotzen ditu, eta ikastaroari ez dagozkion metrikak baztertzen ditu.",
    inside3: "Metrikak, arrisku mailak eta jarraipen seinaleak kalkulatzen ditu konfiguratutako gainditze-atalasea erabilita.",
    inside4: "Emaitza interpretatzeko errazak diren paneletan, grafikoetan eta txostenetan erakusten du.",
    analysisTitle: "Analisiak, grafikoak eta txostenak",
    analysis1: "Ikastaroaren analisi orokorra ikasle kopuruarekin, batez besteko engagement-arekin, entregarekin, jarduera berriarekin eta ikastaroak benetan duenari egokitutako arrisku banaketarekin.",
    analysis2: "Ikasle bakoitzaren analisia arriskuarekin, engagement-arekin, aurrerapenarekin, entregarekin, quiz erabilerarekin, foro parte-hartzearekin eta noten joerarekin, konfiguratutako gutxieneko nota erreferentzia gisa hartuta.",
    analysis3: "Banaketa, konparaketa eta korrelazio grafikoak taldearen portaera begirada batean ulertzeko.",
    analysis4: "Arrisku handiagoa, jarduera txikiagoa edo jarraipen txikiagoa duten ikasleak antzemateko bistaratzeak, nota gainditzetik argi gora dagoenean abisu arinak gehiegi puztu gabe.",
    analysis5: "Ikastaro, ataza eta ikasle txostenak kasu zehatzak berrikusteko, erabilgarri den laburpen batekin eta dauden metriketara egokituta.",
    analysis6: "Norbaitek beste analisi edo txosten mota bat behar badu, eska dezake benetako behar batera egokitzeko.",
    summaryTitle: "Esaldi batean",
    summaryBody: "Moodle Student Analyzer-ek Moodle datuak ikastaro batean gertatzen denaren ikuspegi argi bihurtzen ditu eta lehenengo non jardun erabakitzen laguntzen du.",
  },
};

const defaultLang = "es";
const storageKey = "moodle-analyzer-website-language";

function applyLanguage(lang) {
  const dictionary = translations[lang] || translations[defaultLang];
  document.documentElement.lang = lang;
  document.title = "Moodle Student Analyzer";
  document
    .querySelector('meta[name="description"]')
    .setAttribute("content", dictionary.metaDescription);

  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) {
      node.textContent = dictionary[key];
    }
  });
}

const select = document.getElementById("language-select");
const savedLanguage = localStorage.getItem(storageKey) || defaultLang;
select.value = savedLanguage;
applyLanguage(savedLanguage);

select.addEventListener("change", (event) => {
  const lang = event.target.value;
  localStorage.setItem(storageKey, lang);
  applyLanguage(lang);
});
